disabled_rules: # rule identifiers to exclude from running
  # - colon
included: # paths to include during linting. `--path` is ignored if present.
  - keyn
  # - keynTests
  - keynCredentialProvider
  - keynNotificationExtension
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
force_cast: warning
force_try: warning
identifier_name:
  excluded:
    - id
    - 'n'
    - m
    - 'v1_0'
    - 'v1_1'
line_length: 200
