disabled_rules: # rule identifiers to exclude from running
  - reduce_boolean
included: # paths to include during linting. `--path` is ignored if present.
  - chiff
  # - chiffTests
  # - chiffCredentialProvider
  # - chiffNotificationExtension
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
force_cast: warning
force_try: warning
identifier_name:
  excluded:
    - id
    - 'n'
    - m
    - nc
    - 'v1_0'
    - 'v1_1'
    - os
    - a4
cyclomatic_complexity:
  warning: 12
  ignores_case_statements: true
large_tuple:
  warning: 3
  error: 4
function_parameter_count:
  warning: 7
line_length: 200
