# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc 'Run all tests'
    lane :tests do
        scan(workspace: 'keyn.xcworkspace', scheme: "keyn", devices: ["iPhone 6s"], build_for_testing: true)
    end

    desc 'Build app'
    lane :build_keyn_beta do
        # get_certificates()
        # get_provisioning_profile()
        increment_build_number()
        build_ios_app()
    end

    desc 'Release minor version'
    lane :release_minor_version do
        increment_version_number(bump_type: 'minor')
        build_keyn_beta()
        # test
        # upload
    end

    desc 'Release patch version'
    lane :release_patch_version do
        increment_version_number(bump_type: 'patch')
        build_keyn_beta()
        # test
        # upload
    end

    desc 'Release major version'
    lane :release_major_version do
        increment_version_number(bump_type: 'major')
        build_keyn_beta()
        # test
        # upload
    end
end
